#! /bin/sh

sxhkd &
compton &
udiskie &
odrive &
nm-applet &
blueman-applet &
dunst &

feh --bg-fill ~/Pictures/wall/Mojave-Night.jpg &
~/dotfiles/scripts/keyboard.sh &
~/.config/polybar/nord/launch.sh&
~/dotfiles/scripts/i3-battery-popup.sh -L 20 -n -i ~/dotfiles/pictures/battery.png &

xsetroot -cursor_name left_ptr &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config top_padding 0
bspc config bottom_padding 33

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
